services:
  metadata-scraper:
    image: ghcr.io/lostontheline/anime-dub-calendar:latest
    container_name: metadata_scraper
    environment:
      - dub_streaming_50607=DisneyNow
    volumes:
      - /volume1/docker/metadata_scraper/data:/data
    ports:
      - "5000:5000"  # Expose Flask app
    restart: unless-stopped