services:
  metadata-scraper:
    image: ghcr.io/lostontheline/anime-dub-calendar:latest
    container_name: metadata_scraper
    environment:
      - dub_streaming_50607=DisneyNow
      - GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  # Replace with your PAT
      - SYNC_INTERVAL_HOURS=1  # Default to 1 hour
    volumes:
      - /volume1/docker/metadata_scraper/data:/data
    ports:
      - "5000:5000"
    restart: unless-stopped