name: Fetch

on:
#  schedule:
#    - cron: '0 8 1 1 1'  # 8:00 AM UTC daily '0 8 * * *' #Updated to prevent broken runs 
  workflow_dispatch:  # Manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Grok

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run creds
        env:
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" | base64 -d > credentials.json
          rm credentials.json  # Remove temp file to avoid exposure
