name: Update Shows

on:
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Check initial database file status
        run: echo "Initial database file status:" && ls -l shows.db

      - name: Update shows
        run: python -c "import main; import asyncio; asyncio.run(main.update_shows())"

      - name: Check database file status after update
        run: echo "Database file status after update:" && ls -l shows.db

      - name: Configure Git
        run: git config --global user.name "GitHub Action"

      - name: Commit changes to shows.db
        run: |
          git add shows.db
          git commit -m "Update shows.db [skip ci]" || echo "No changes to commit in shows.db."

      - name: Ignore __pycache__ if not already present
        run: |
          if ! grep -Fxq "__pycache__/" .gitignore; then
            echo "__pycache__/" >> .gitignore
            git add .gitignore
            git commit -m "Add __pycache__ to .gitignore [skip ci]" || echo "No changes to commit"
          else
            echo "__pycache__ already ignored in .gitignore"
          fi

      - name: Push changes
        run: git push