name: Update Anime Dub Schedule
on:
  schedule:
    - cron: "0 8 * * *"  # 8 AM UTC (midnight PST)
  workflow_dispatch:  # Manual trigger option
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('main.py') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Debug cache hit
      #  run: echo "Cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"
        run: echo "Cache hit: true"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        run: python main.py