name: Update Anime Dub Calendar

on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC daily
  workflow_dispatch:  # Manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Grok

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run calendar updater
        env:
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" | base64 -d > credentials.json
          python src/calendar_updater.py
          rm credentials.json  # Remove temp file to avoid exposure

      - name: Commit updated data
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data/parsed_data.yaml
          git commit -m "Update parsed data - $(date -u +%Y-%m-%d)" || echo "No changes to commit"
          git push